stages:
  - build

powershell_script:
  stage: build
  tags: 
    - Shell-Maven
  script:
    - powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File generated-windows-powershell.ps1
    - powershell -ExecutionPolicy Bypass -File "C:\Gitlab-Runner\builder.ps1"