image: maven:3.6.3

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - clean
  - build
  - test
  - deploy

before_script:
  - chmod +x mvnw

clean:
  stage: clean
  script:
    - ./mvnw clean

build:
  stage: build
  script:
    - ./mvnw package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - ./mvnw test

deploy:
  stage: deploy
  script:
    - echo "Deployment completed!"
  only:
    - develop