variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - clean
  - build
  - test
  - deploy

before_script:
  - chmod +x mvnw

clean:
  stage: clean
  script:
    - mvn clean

build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - echo "Deployment completed!"
  only:
    - develop