variables:
  # Define as variáveis de ambiente para o JDK 1.8 e o Maven 3.6.3
  MAVEN_VERSION: "3.6.3"
  MAVEN_HOME: "/opt/maven"
  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  PATH: "/opt/maven/bin:$PATH"

stages:
  - clean
  - package
  - deploy

clean:
  stage: clean
  script:
    - mvn clean

package:
  stage: package
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    # Coloque aqui os comandos de implantação do seu aplicativo
    - echo "Implantação do aplicativo aqui"]

# test
