param 
(
  [Parameter(Mandatory=$true)] [String]$exepath
)

$exepath = "C:\dev\repos\git\Integration_Project\target\jfx\native\Integration_Project-1.0-SNAPSHOT.exe"

$sharedDirectory = "\\EINSTEIN\Integration_Project-1.0-SNAPSHOT"

mvn clean package

Copy-Item $exepath $sharedDirectory