image: maven:3.6.3

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - clean
  - package
  - install
  - deploy

before_script:
  - chmod +x mvnw

clean:
  stage: clean
  script: ./mvnw clean

package:
  stage: package
  script: ./mvnw package
  artifacts:
    paths:
      - target/Integration_Project-1.0-SNAPSHOT.jar

install:
  stage: install
  script: ./mvnw install

deploy:
  stage: deploy
  script: 
    - echo "Deploy concluído!"
  only: 
    - develop

